import { Button } from '@/components/ui/button'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Youtube',
  description: 'Generated by create next app'
}

const Home = () => {
  return <Button>HomePage</Button>
}

export default Home
