import { Metadata } from 'next'

import HomePage from '@/components/home-page'

export const metadata: Metadata = {
  title: 'Youtube',
  description: 'Generated by create next app'
}

const Home = () => {
  return <HomePage />
}

export default Home
