import type { Metadata } from 'next'
import { Chivo as FontSans } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'react-hot-toast'

import AppProvider from '@/providers/app-provider'
import TanstackProvider from '@/providers/tanstack-provider'
import ThemeProvider from '@/providers/theme-provider'
import WatchProvider from '@/providers/watch-provider'
import './globals.css'

export const fontSans = FontSans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootLayoutProps = {
  children: React.ReactNode
  uploadVideo: React.ReactNode
}

const RootLayout = ({ children, uploadVideo }: RootLayoutProps) => {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={fontSans.className}>
        <TanstackProvider>
          <AppProvider>
            <ThemeProvider attribute='class' defaultTheme='system'>
              <WatchProvider>
                {children}
                {uploadVideo}
                <Toaster toastOptions={{ className: 'text-[15px]' }} />
                <NextTopLoader color='red' height={2} showSpinner={false} shadow={false} />
              </WatchProvider>
            </ThemeProvider>
          </AppProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}

export default RootLayout
