import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'

import { Toaster } from '@/components/ui/toaster'
import AppProvider from '@/providers/app-provider'
import TanstackProvider from '@/providers/tanstack-provider'
import ThemeProvider from '@/providers/theme-provider'
import './globals.css'

export const fontSans = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootLayoutProps = {
  children: React.ReactNode
  uploadVideo: React.ReactNode
}

const RootLayout = ({ children, uploadVideo }: RootLayoutProps) => {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={fontSans.className}>
        <TanstackProvider>
          <AppProvider>
            <ThemeProvider attribute='class' defaultTheme='system'>
              {children}
              {uploadVideo}
              <Toaster />
              <NextTopLoader color='red' height={2} showSpinner={false} shadow={false} />
            </ThemeProvider>
          </AppProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}

export default RootLayout
