import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { Toaster } from '@/components/ui/toaster'
import AppProvider from '@/providers/app-provider'
import TanstackProvider from '@/providers/tanstack-provider'
import ThemeProvider from '@/providers/theme-provider'
import './globals.css'

export const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={roboto.className}>
        <TanstackProvider>
          <AppProvider>
            <ThemeProvider attribute='class' defaultTheme='system'>
              {children}
              <Toaster />
            </ThemeProvider>
          </AppProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
