import type { Metadata } from 'next'
import Link from 'next/link'

import LoginForm from '@/components/login-form'

export const metadata: Metadata = {
  title: 'Đăng nhập',
  description: 'Generated by create next app'
}

const Login = () => {
  return (
    <div className='mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]'>
      <div className='flex flex-col space-y-2 text-center'>
        <h1 className='text-2xl font-semibold tracking-tight'>Đăng nhập</h1>
        <p className='text-sm text-muted-foreground'>Nhập tài khoản và mật khẩu để đăng nhập</p>
      </div>
      <LoginForm />
      <p className='text-right text-sm text-muted-foreground'>
        <Link href='/terms' className='underline underline-offset-4 hover:text-primary'>
          Quên mật khẩu
        </Link>
      </p>
    </div>
  )
}

export default Login
